### ISSUE TITLE
The ERROR about Relevance feedback command

### ISSUE THREAD

**Issue by winycg** [terrier-org/terrier-core#10]
When I run relevance feedback command, the error will be emerge:
$bin/terrier batchretrieval -q -Dqe.feedback.selector=RelevantOnlyFeedbackDocuments,RelevanceFeedbackSelector -Dqe.feedback.filename=/home/winycg/msd/terrier/qrels-final-trials.txt
Exception in thread "main" java.util.NoSuchElementException: No reverse lookup for key docno is supported
	at org.terrier.structures.CompressingMetaIndex.getDocument(CompressingMetaIndex.java:669)
	at org.terrier.querying.RelevanceFeedbackSelector.getFeedbackDocuments(RelevanceFeedbackSelector.java:109)
	at org.terrier.querying.RelevantOnlyFeedbackDocuments.getFeedbackDocuments(RelevantOnlyFeedbackDocuments.java:59)
	at org.terrier.querying.QueryExpansion.expandQuery(QueryExpansion.java:130)
	at org.terrier.querying.QueryExpansion.process(QueryExpansion.java:292)
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:832)
	at org.terrier.applications.batchquerying.TRECQuerying.processQuery(TRECQuerying.java:715)
	at org.terrier.applications.batchquerying.TRECQuerying.processQueryAndWrite(TRECQuerying.java:626)
	at org.terrier.applications.batchquerying.TRECQuerying.processQueries(TRECQuerying.java:825)
	at org.terrier.applications.batchquerying.TRECQuerying.processQueries(TRECQuerying.java:738)
	at org.terrier.applications.batchquerying.TRECQuerying$Command.run(TRECQuerying.java:252)
	at org.terrier.applications.AbstractQuerying$AbstractQueryingCommand.run(AbstractQuerying.java:159)
	at org.terrier.applications.CLITool$CLIParsedCLITool.run(CLITool.java:130)
	at org.terrier.applications.CLITool.main(CLITool.java:244)

Note that the other operations by terrier have no problems.

**Comment by cmacdonald** [comment]
You need to enable reverse meta keys of docno during indexing. Check the indexing documentation.
Craig

Sent from my iPhone

On 8 Dec 2018, at 08:29, winycg <notifications@github.com<mailto:notifications@github.com>> wrote:


When I run relevance feedback command, the error will be emerge:
Exception in thread "main" java.util.NoSuchElementException: No reverse lookup for key docno is supported
at org.terrier.structures.CompressingMetaIndex.getDocument(CompressingMetaIndex.java:669)
at org.terrier.querying.RelevanceFeedbackSelector.getFeedbackDocuments(RelevanceFeedbackSelector.java:109)
at org.terrier.querying.RelevantOnlyFeedbackDocuments.getFeedbackDocuments(RelevantOnlyFeedbackDocuments.java:59)
at org.terrier.querying.QueryExpansion.expandQuery(QueryExpansion.java:130)
at org.terrier.querying.QueryExpansion.process(QueryExpansion.java:292)
at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:832)
at org.terrier.applications.batchquerying.TRECQuerying.processQuery(TRECQuerying.java:715)
at org.terrier.applications.batchquerying.TRECQuerying.processQueryAndWrite(TRECQuerying.java:626)
at org.terrier.applications.batchquerying.TRECQuerying.processQueries(TRECQuerying.java:825)
at org.terrier.applications.batchquerying.TRECQuerying.processQueries(TRECQuerying.java:738)
at org.terrier.applications.batchquerying.TRECQuerying$Command.run(TRECQuerying.java:252)
at org.terrier.applications.AbstractQuerying$AbstractQueryingCommand.run(AbstractQuerying.java:159)
at org.terrier.applications.CLITool$CLIParsedCLITool.run(CLITool.java:130)
at org.terrier.applications.CLITool.main(CLITool.java:244)

Note that the other operations by terrier have no problems.

**Comment by winycg** [comment]
Thanks!The problem is solved because I forget to configure 'indexer.meta.reverse.keys=docno'.
