### ISSUE TITLE
Transient Structure Merging CI failure

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/terrier-core#109]
```
2020-05-06T12:27:45.8672370Z java.io.EOFException: null
2020-05-06T12:27:45.8672470Z 	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272) ~[na:na]
2020-05-06T12:27:45.8675310Z 	at org.apache.hadoop.io.WritableUtils.readVLong(WritableUtils.java:308) ~[hadoop-common-2.8.2.jar:na]
2020-05-06T12:27:45.8681230Z 	at org.apache.hadoop.io.WritableUtils.readVInt(WritableUtils.java:329) ~[hadoop-common-2.8.2.jar:na]
2020-05-06T12:27:45.8681820Z 	at org.apache.hadoop.io.Text.readFields(Text.java:290) ~[hadoop-common-2.8.2.jar:na]
2020-05-06T12:27:45.8682370Z 	at org.terrier.structures.seralization.FixedSizeTextFactory$FixedSizeText.readFields(FixedSizeTextFactory.java:66) ~[terrier-core-5.3-SNAPSHOT.jar:na]
2020-05-06T12:27:45.8686270Z 	at org.terrier.structures.collections.FSOrderedMapFile$EntryIterator.next(FSOrderedMapFile.java:230) ~[terrier-core-5.3-SNAPSHOT.jar:na]
2020-05-06T12:27:45.8687420Z 	at org.terrier.structures.collections.FSOrderedMapFile$EntryIterator.next(FSOrderedMapFile.java:167) ~[terrier-core-5.3-SNAPSHOT.jar:na]
2020-05-06T12:27:45.8688740Z 	at org.terrier.structures.FSOMapFileLexicon$MapFileLexiconIterator.next(FSOMapFileLexicon.java:195) ~[terrier-core-5.3-SNAPSHOT.jar:na]
2020-05-06T12:27:45.8689610Z 	at org.terrier.structures.FSOMapFileLexicon$MapFileLexiconIterator.next(FSOMapFileLexicon.java:164) ~[terrier-core-5.3-SNAPSHOT.jar:na]
2020-05-06T12:27:45.8692540Z 	at org.terrier.structures.merging.StructureMerger.mergeInvertedFiles(StructureMerger.java:284) ~[terrier-batch-indexers-5.3-SNAPSHOT.jar:na]
2020-05-06T12:27:45.8695120Z 	at org.terrier.structures.merging.StructureMerger.mergeStructures(StructureMerger.java:688) ~[terrier-batch-indexers-5.3-SNAPSHOT.jar:na]
2020-05-06T12:27:45.8697380Z 	at org.terrier.structures.merging.TestMerger.test111_blocks(TestMerger.java:56) ~[test-classes/:na]
2020-05-06T12:27:45.8699090Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2020-05-06T12:27:45.8701330Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
2020-05-06T12:27:45.8704280Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
2020-05-06T12:27:45.8706300Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
2020-05-06T12:27:45.8709900Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8712230Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8714590Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8716310Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8717940Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8720000Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8721710Z 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:43) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8723630Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8725060Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8726800Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8728160Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8729460Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8731710Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8732540Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8734910Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:236) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8736650Z 	at org.junit.runners.Suite.runChild(Suite.java:128) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8738140Z 	at org.junit.runners.Suite.runChild(Suite.java:24) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8739420Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8741670Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8743480Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8744740Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8746560Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8747930Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:236) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8750320Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:344) ~[surefire-junit4-2.19.jar:2.19]
2020-05-06T12:27:45.8753330Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:269) ~[surefire-junit4-2.19.jar:2.19]
2020-05-06T12:27:45.8755450Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:240) ~[surefire-junit4-2.19.jar:2.19]
2020-05-06T12:27:45.8757120Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:184) ~[surefire-junit4-2.19.jar:2.19]
2020-05-06T12:27:45.8760030Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286) ~[surefire-booter-2.19.jar:2.19]
2020-05-06T12:27:45.8761920Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240) ~[surefire-booter-2.19.jar:2.19]
2020-05-06T12:27:45.8764010Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121) ~[surefire-booter-2.19.jar:2.19]
2020-05-06T12:27:45.8765900Z 12:27:45.867 [main] ERROR o.t.s.merging.StructureMerger - Problem while merging lexicons and inverted files.
2020-05-06T12:27:45.8766380Z java.util.NoSuchElementException: IOException while iterating
2020-05-06T12:27:45.8770290Z 	at org.terrier.structures.collections.FSOrderedMapFile$EntryIterator.next(FSOrderedMapFile.java:235) ~[terrier-core-5.3-SNAPSHOT.jar:na]
2020-05-06T12:27:45.8772950Z 	at org.terrier.structures.collections.FSOrderedMapFile$EntryIterator.next(FSOrderedMapFile.java:167) ~[terrier-core-5.3-SNAPSHOT.jar:na]
2020-05-06T12:27:45.8775720Z 	at org.terrier.structures.FSOMapFileLexicon$MapFileLexiconIterator.next(FSOMapFileLexicon.java:195) ~[terrier-core-5.3-SNAPSHOT.jar:na]
2020-05-06T12:27:45.8778260Z 	at org.terrier.structures.FSOMapFileLexicon$MapFileLexiconIterator.next(FSOMapFileLexicon.java:164) ~[terrier-core-5.3-SNAPSHOT.jar:na]
2020-05-06T12:27:45.8780770Z 	at org.terrier.structures.merging.StructureMerger.mergeInvertedFiles(StructureMerger.java:284) ~[terrier-batch-indexers-5.3-SNAPSHOT.jar:na]
2020-05-06T12:27:45.8783850Z 	at org.terrier.structures.merging.StructureMerger.mergeStructures(StructureMerger.java:688) ~[terrier-batch-indexers-5.3-SNAPSHOT.jar:na]
2020-05-06T12:27:45.8785500Z 	at org.terrier.structures.merging.TestMerger.test111_blocks(TestMerger.java:56) ~[test-classes/:na]
2020-05-06T12:27:45.8787250Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2020-05-06T12:27:45.8789560Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
2020-05-06T12:27:45.8791640Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
2020-05-06T12:27:45.8792890Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
2020-05-06T12:27:45.8795720Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8798280Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8799930Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8802580Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8804410Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8805970Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8807640Z 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:43) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8810180Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8811560Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8813070Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8815060Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8816200Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8818560Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8820390Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8822290Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:236) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8823670Z 	at org.junit.runners.Suite.runChild(Suite.java:128) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8824500Z 	at org.junit.runners.Suite.runChild(Suite.java:24) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8825420Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8825970Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8826960Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8829170Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8831400Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8832290Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:236) ~[junit-4.8.1.jar:na]
2020-05-06T12:27:45.8834650Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:344) ~[surefire-junit4-2.19.jar:2.19]
2020-05-06T12:27:45.8837100Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:269) ~[surefire-junit4-2.19.jar:2.19]
2020-05-06T12:27:45.8839060Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:240) ~[surefire-junit4-2.19.jar:2.19]
2020-05-06T12:27:45.8841500Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:184) ~[surefire-junit4-2.19.jar:2.19]
2020-05-06T12:27:45.8844750Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286) ~[surefire-booter-2.19.jar:2.19]
2020-05-06T12:27:45.8846650Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240) ~[surefire-booter-2.19.jar:2.19]
2020-05-06T12:27:45.8848310Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121) ~[surefire-booter-2.19.jar:2.19]
2020-05-06T12:27:45.8849570Z java.util.NoSuchElementException: IOException while iterating
2020-05-06T12:27:45.8851610Z 	at org.terrier.structures.collections.FSOrderedMapFile$EntryIterator.next(FSOrderedMapFile.java:235)
2020-05-06T12:27:45.8853390Z 	at org.terrier.structures.collections.FSOrderedMapFile$EntryIterator.next(FSOrderedMapFile.java:167)
2020-05-06T12:27:45.8855260Z 	at org.terrier.structures.FSOMapFileLexicon$MapFileLexiconIterator.next(FSOMapFileLexicon.java:195)
2020-05-06T12:27:45.8857720Z 	at org.terrier.structures.FSOMapFileLexicon$MapFileLexiconIterator.next(FSOMapFileLexicon.java:164)
2020-05-06T12:27:45.8859620Z 	at org.terrier.structures.merging.StructureMerger.mergeInvertedFiles(StructureMerger.java:284)
2020-05-06T12:27:45.8861370Z 	at org.terrier.structures.merging.StructureMerger.mergeStructures(StructureMerger.java:688)
2020-05-06T12:27:45.8862620Z 	at org.terrier.structures.merging.TestMerger.test111_blocks(TestMerger.java:56)
2020-05-06T12:27:45.8864270Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-05-06T12:27:45.8866190Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-05-06T12:27:45.8868610Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-05-06T12:27:45.8869240Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
2020-05-06T12:27:45.8870810Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
2020-05-06T12:27:45.8873380Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
2020-05-06T12:27:45.8874830Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
2020-05-06T12:27:45.8876990Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
2020-05-06T12:27:45.8878480Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
2020-05-06T12:27:45.8879610Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
2020-05-06T12:27:45.8881230Z 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:43)
2020-05-06T12:27:45.8882870Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
2020-05-06T12:27:45.8884720Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
2020-05-06T12:27:45.8885500Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
2020-05-06T12:27:45.8887260Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
2020-05-06T12:27:45.8888050Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
2020-05-06T12:27:45.8890830Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
2020-05-06T12:27:45.8891380Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
2020-05-06T12:27:45.8891800Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
2020-05-06T12:27:45.8893700Z 	at org.junit.runners.Suite.runChild(Suite.java:128)
2020-05-06T12:27:45.8894150Z 	at org.junit.runners.Suite.runChild(Suite.java:24)
2020-05-06T12:27:45.8895960Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
2020-05-06T12:27:45.8896790Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
2020-05-06T12:27:45.8898790Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
2020-05-06T12:27:45.8899930Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
2020-05-06T12:27:45.8901630Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
2020-05-06T12:27:45.8902210Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
2020-05-06T12:27:45.8904010Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:344)
2020-05-06T12:27:45.8906010Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:269)
2020-05-06T12:27:45.8908320Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:240)
2020-05-06T12:27:45.8909910Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:184)
2020-05-06T12:27:45.8911900Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
2020-05-06T12:27:45.8913420Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
2020-05-06T12:27:45.8914750Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
2020-05-06T12:27:45.8925020Z 
```

**Comment by cmacdonald** [comment]
No longer being observed. Will close.
