### ISSUE TITLE
FLATJsonDocument consumes parsing exceptions

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/terrier-core#215]
If I pass `['a', 'b']` to FLATJsonDocument it only displays an exception, when probably it should escalate.

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"["a", "b"]"; line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:222)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:447)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
        at org.terrier.indexing.FlatJSONDocument.initalize(FlatJSONDocument.java:75)
        at org.terrier.indexing.FlatJSONDocument.<init>(FlatJSONDocument.java:65)
<org.terrier.indexing.FlatJSONDocument at 0x7fcda0400c70 jclass=org/terrier/indexing/FlatJSONDocument jself=<LocalRef obj=0x7fcd4e72ca90 at 0x7fcda03efdd0>>
```

**Comment by cmacdonald** [comment]
Originally reported by @seanmacavaney in https://github.com/terrier-org/pyterrier/pull/349#issuecomment-1339907292
