### ISSUE TITLE
Not able to index non-english corpus

### ISSUE THREAD

**Issue by sainikanuj** [terrier-org/terrier-core#69]
I have used trec.collection.class=TRECUTFCollection as a property in the terrier.properties file but when i try to index it gives following error.

Setting TERRIER_HOME to /home/anuj/terrier_5.2_hin
16:06:35.873 [main] INFO  o.terrier.indexing.CollectionFactory - Finished reading collection specification
16:06:35.899 [main] INFO  o.t.i.MultiDocumentFileCollection - TRECUTFCollection 0% processing ../thesis/corpora/hi.docs.2010/amar_ujala/default_cur_10_date_10_11_2005.utf8
16:06:35.903 [main] ERROR o.terrier.indexing.CollectionFactory - ERROR: First Collection class named org.terrier.indexing.TRECUTFCollection  - cannot be instantiated
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_221]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_221]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_221]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_221]
	at org.terrier.indexing.CollectionFactory.loadCollections(CollectionFactory.java:97) [terrier-project-5.2-jar-with-dependencies.jar:na]
	at org.terrier.indexing.CollectionFactory.loadCollection(CollectionFactory.java:76) [terrier-project-5.2-jar-with-dependencies.jar:na]
	at org.terrier.applications.TRECIndexing.loadCollection(TRECIndexing.java:98) [terrier-project-5.2-jar-with-dependencies.jar:na]
	at org.terrier.applications.TRECIndexing.<init>(TRECIndexing.java:68) [terrier-project-5.2-jar-with-dependencies.jar:na]
	at org.terrier.applications.TRECIndexing.<init>(TRECIndexing.java:56) [terrier-project-5.2-jar-with-dependencies.jar:na]
	at org.terrier.applications.BatchIndexing$Command.run(BatchIndexing.java:114) [terrier-project-5.2-jar-with-dependencies.jar:na]
	at org.terrier.applications.CLITool$CLIParsedCLITool.run(CLITool.java:199) [terrier-project-5.2-jar-with-dependencies.jar:na]
	at org.terrier.applications.CLITool.main(CLITool.java:376) [terrier-project-5.2-jar-with-dependencies.jar:na]
Caused by: java.lang.UnsupportedOperationException: TRECUTFCollection is deprecated. Use TRECCollection and the tokeniser property instead
	at org.terrier.indexing.TRECUTFCollection.<init>(TRECUTFCollection.java:60) ~[terrier-project-5.2-jar-with-dependencies.jar:na]
	... 12 common frames omitted
Exception in thread "main" java.lang.IllegalArgumentException: Collection class named TRECUTFCollection not loaded, aborting
	at org.terrier.applications.TRECIndexing.loadCollection(TRECIndexing.java:101)
	at org.terrier.applications.TRECIndexing.<init>(TRECIndexing.java:68)
	at org.terrier.applications.TRECIndexing.<init>(TRECIndexing.java:56)
	at org.terrier.applications.BatchIndexing$Command.run(BatchIndexing.java:114)
	at org.terrier.applications.CLITool$CLIParsedCLITool.run(CLITool.java:199)
	at org.terrier.applications.CLITool.main(CLITool.java:376)

**Comment by cmacdonald** [comment]
the error tells you _exactly_ what is wrong.
