### ISSUE TITLE
IndexUtil options are not working

### ISSUE THREAD

**Issue by mrgrassho** [terrier-org/terrier-core#97]
### Description

I was trying to run `bin/terrier indexutil --printmeta meta` and this error show up:

```
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --printmeta
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360)
        at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:407)
        at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:384)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:239)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at org.terrier.applications.CLITool$CLIParsedCLITool.run(CLITool.java:149)
        at org.terrier.applications.CLITool.main(CLITool.java:376)
```
If a run `bin/terrier indexutil help`

```bash
Usage: org.terrier.structures.IndexUtil {--printbitfile|--printlex|--printdocument|--printlist|--printmeta} structureName
```

It shows that `--printmeta` is indeed a valid option.

### Solution:

After a while, I figured out that `--printmeta` is working as `-printmeta`  (single dash). The same applies to all options.

------

Version: 5.2
Platform: macOS Catalina

**Comment by cmacdonald** [comment]
Thanks for the report. We identified this a few weeks back - see #78 - its now fixed in github for the next version 5.3
