### ISSUE TITLE
Indexing_Crash

### ISSUE THREAD

**Issue by stamatisvas** [terrier-org/terrier-core#99]
Using the github version of terrier I getting this error at 89%. I checked cpu and ram usage and at the start is cpu=40-70% (intel Xeon E5620)and ram=30% (My ram at 100% is 10GB) and after many hours of indexing the cpu is between 100-200% and ram still the same.

00:43:57.506 [main] INFO  o.t.i.MultiDocumentFileCollection - TRECCollection 89% processing /home/spare1/SGML/89/008.txt
00:43:57.541 [main] INFO  o.t.i.MultiDocumentFileCollection - TRECCollection 89% processing /home/spare1/SGML/89/014.txt
00:43:57.612 [main] INFO  o.t.i.MultiDocumentFileCollection - TRECCollection 89% processing /home/spare1/SGML/89/016.txt

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at gnu.trove.TObjectIntHashMap.rehash(TObjectIntHashMap.java:170)
        at gnu.trove.THash.postInsertHook(THash.java:359)
        at gnu.trove.TObjectIntHashMap.put(TObjectIntHashMap.java:155)
        at org.terrier.utility.TermCodes.getCode(TermCodes.java:99)
        at org.terrier.structures.indexing.DocumentPostingList$2.execute(DocumentPostingList.java:177)
        at org.terrier.structures.indexing.DocumentPostingList$2.execute(DocumentPostingList.java:174)
        at gnu.trove.TObjectIntHashMap.forEachEntry(TObjectIntHashMap.java:426)
        at org.terrier.structures.indexing.DocumentPostingList.getPostings2(DocumentPostingList.java:174)
        at org.terrier.structures.indexing.classical.BasicIndexer.indexDocument(BasicIndexer.java:382)
        at org.terrier.structures.indexing.classical.BasicIndexer.createDirectIndex(BasicIndexer.java:285)
        at org.terrier.structures.indexing.Indexer.index(Indexer.java:366)
        at org.terrier.applications.TRECIndexing.index(TRECIndexing.java:155)
        at org.terrier.applications.BatchIndexing$Command.run(BatchIndexing.java:120)
        at org.terrier.applications.CLITool$CLIParsedCLITool.run(CLITool.java:199)
        at org.terrier.applications.CLITool.main(CLITool.java:376)

**Comment by cmacdonald** [comment]
You can control how much memory Terrier can access using the TERRIER_HEAP_MEM env variable. If you still struggle, you can try using the single pass indexer, c.f. `bin/terrier bi -j`

**Comment by cmacdonald** [comment]
No further response received, closing.
